import { currentUser } from './student-cloud';
import { claimInitialContentAdmin, claimReviewerInvite, correctQuarantinedQuestion, createReviewerInvite, listReviewerTeam, publishQuestion, resolveReport, reviewQuestion, reviewerQuestion, reviewerQueue, reviewerStatus, setReviewerByEmail, type ReviewerQuestion, type ReviewerQueueItem, type ReviewerTeamMember } from './trust';

const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let role:string|null=null; let selectedId:string|null=null; let items:ReviewerQueueItem[]=[];

function refText(ref:any){if(typeof ref==='string')return ref;const parts=[ref?.title,ref?.book,ref?.guideline,ref?.edition&&`Edition ${ref.edition}`,ref?.chapter&&`Chapter ${ref.chapter}`,ref?.year,ref?.url].filter(Boolean);return parts.length?parts.join(' · '):JSON.stringify(ref);}
function evidenceFromText(raw:string){const sources=raw.split('\n').map(x=>x.trim()).filter(Boolean).map(citation=>({citation}));return sources.length?{sources,reviewed_at:new Date().toISOString()}:null;}

async function init(){
 const user=await currentUser();
 if(!user){$('gateMsg').textContent='Sign in through My Progress, then return with a reviewer-authorized account.';$('claimBox').classList.add('hidden');$('inviteBox').classList.add('hidden');return;}
 try{
  const s=await reviewerStatus();
  if(!s.authorized){$('gateMsg').textContent='This signed-in account is not assigned to the SurgiQuiz medical review team. Use an invitation code, or the one-time initial administrator code if you are setting up the first reviewer account.';$('claimBox').classList.remove('hidden');$('inviteBox').classList.remove('hidden');return;}
  role=s.role;$('role').textContent=`Reviewer · ${String(role).replaceAll('_',' ')}`;$('gate').classList.add('hidden');$('workspace').classList.remove('hidden');
  $('teamCard').classList.toggle('hidden',role!=='admin');
  await Promise.all([loadQueue(),role==='admin'?loadTeam():Promise.resolve()]);
 }catch(e:any){$('gateMsg').textContent=e.message||'Unable to validate reviewer access.';}
}

async function loadQueue(){const status=($<HTMLSelectElement>('statusFilter')).value||null;const tier=($<HTMLSelectElement>('tierFilter')).value||null;const box=$('queue');box.textContent='Loading review queue…';try{items=await reviewerQueue(60,status,tier);renderQueue();if(selectedId&&!items.some(x=>x.id===selectedId)){selectedId=null;$('detail').innerHTML='<div class="muted">Select a question from the queue.</div>';}}catch(e:any){box.textContent=e.message||'Unable to load review queue.';}}

function renderQueue(){const box=$('queue');box.innerHTML=items.length?items.map(x=>`<div class="qitem ${selectedId===x.id?'active':''}" data-id="${esc(x.id)}"><div class="qhead"><b>#${x.queue_index}</b><span class="badge">${esc(x.status)}</span></div><div>${esc(x.category||'General Surgery')}</div><div class="muted">${esc(x.topic||'')} · ${esc(x.review_tier)}${x.open_reports?` · ${x.open_reports} open report${x.open_reports===1?'':'s'}`:''}</div></div>`).join(''):'<div class="muted">No questions match the current filters.</div>';box.querySelectorAll<HTMLElement>('[data-id]').forEach(el=>el.onclick=()=>openQuestion(el.dataset.id!));}

async function openQuestion(id:string){selectedId=id;renderQueue();const box=$('detail');box.textContent='Loading question…';try{const d=await reviewerQuestion(id);renderDetail(d);}catch(e:any){box.textContent=e.message||'Unable to load question.';}}

function renderDetail(d:ReviewerQuestion){
 const q=d.question;const anomaly=q.review_tier==='quarantine_source_answer_anomaly';const needsEvidence=q.review_tier==='evidence_review_required';
 const reports=(d.reports||[]).map((r:any)=>`<div class="report"><div class="qhead"><b>${esc(r.type)}</b><span class="badge">${esc(r.status)}</span></div><div>${esc(r.notes||'No notes')}</div><div class="muted">${new Date(r.created_at).toLocaleString()}</div>${r.status==='open'||r.status==='triaged'?`<div class="actions" style="margin-top:8px"><button data-report="${esc(r.id)}" data-report-status="triaged">Triage</button><button data-report="${esc(r.id)}" data-report-status="resolved" class="primary">Resolve</button><button data-report="${esc(r.id)}" data-report-status="dismissed">Dismiss</button></div>`:''}</div>`).join('')||'<div class="muted">No learner reports.</div>';
 const refs=(d.references||[]).map((r:any,i:number)=>`<div class="ref"><b>${i+1}.</b> ${esc(refText(r))}</div>`).join('')||'<div class="muted">No references attached.</div>';
 const history=(d.reviews||[]).map((r:any)=>`<div class="history"><b>${esc(r.decision)}</b> · ${esc(r.review_type)}<div>${esc(r.notes||'')}</div><div class="muted">${new Date(r.created_at).toLocaleString()}</div></div>`).join('')||'<div class="muted">No prior review decisions.</div>';
 const versions=(d.versions||[]).map((v:any)=>`<span class="badge">v${v.version} · ${esc(v.reason||'snapshot')}</span>`).join(' ')||'<span class="muted">No version snapshots yet.</span>';
 const correction=anomaly&&(role==='lead_reviewer'||role==='admin')?`<section class="panel decision correction"><h3>Evidence-based quarantine correction</h3><p class="muted">Correct the keyed answer only after independent evidence review. Saving this does not verify or publish the question; it returns the item to Evidence Review.</p><select id="correctedIndex">${(d.options||[]).map((o:any)=>`<option value="${o.index}" ${o.index===q.correct_index?'selected':''}>${String.fromCharCode(65+Number(o.index))}. ${esc(o.en)}</option>`).join('')}</select><textarea id="correctedExplanation" placeholder="Corrected explanation (required)">${esc(q.en_explanation||'')}</textarea><textarea id="correctedLearning" placeholder="Corrected learning point (required)">${esc(q.en_learning_point||'')}</textarea><textarea id="correctionEvidence" placeholder="Required: one current independent evidence source per line"></textarea><textarea id="correctionNotes" placeholder="Why this answer/content was corrected"></textarea><button id="saveCorrection" class="secondary">Save correction & return to Evidence Review</button><div id="correctionMsg" class="muted"></div></section>`:'';
 $('detail').innerHTML=`<div class="qhead"><div><span class="badge">#${q.queue_index}</span> <span class="badge">${esc(q.category)}</span> <span class="badge">${esc(q.evidence_status)}</span></div><div><span class="badge">${esc(q.review_tier)}</span> <span class="badge">v${q.content_version}</span></div></div>${anomaly?'<section class="card notice"><b>Quarantined source-answer anomaly</b><p class="muted">This item cannot be approved or published until the answer/content is corrected through the evidence-based workflow below.</p></section>':''}<h2 class="stem">${esc(q.en_stem)}</h2>${q.ar_stem?`<p dir="rtl">${esc(q.ar_stem)}</p>`:''}<section class="panel"><h3>Options & rationales</h3><div class="options">${(d.options||[]).map((o:any)=>`<div class="option ${o.index===q.correct_index?'correct':''}"><b>${String.fromCharCode(65+Number(o.index))}. ${esc(o.en)}</b>${o.ar?`<div dir="rtl">${esc(o.ar)}</div>`:''}<div class="muted" style="margin-top:7px">${o.index===q.correct_index?'Current keyed answer · ':''}${esc(o.en_rationale||'No rationale')}</div></div>`).join('')}</div></section><section class="panel"><h3>Explanation</h3><p>${esc(q.en_explanation||'No explanation')}</p><h3>Learning point</h3><p>${esc(q.en_learning_point||'No learning point')}</p></section><section class="panel"><h3>References</h3>${refs}</section>${correction}<section class="panel"><h3>Learner reports</h3>${reports}</section><section class="panel"><h3>Review history</h3>${history}<div style="margin-top:8px">${versions}</div></section><section class="panel decision"><h3>Medical review decision</h3><textarea id="reviewNotes" placeholder="Reviewer notes, corrections needed, or medical rationale…"></textarea>${needsEvidence?'<textarea id="evidenceNotes" placeholder="Required for approval: one CURRENT evidence source per line — guideline/article/book edition + year and URL/DOI when available"></textarea>':'<textarea id="evidenceNotes" placeholder="Optional: one evidence source per line"></textarea>'}<div class="actions">${!anomaly?'<button id="approve" class="primary">Approve as medically verified</button>':''}<button id="changes" class="warn">Needs changes</button><button id="reject" class="danger">Reject</button>${q.status==='verified'&&(role==='lead_reviewer'||role==='admin')?'<button id="publish" class="secondary">Publish to Verified QBank</button>':''}</div><div id="decisionMsg" class="muted"></div></section>`;
 bindDetail(q,needsEvidence,anomaly);
}

function evidencePayload(required:boolean){const payload=evidenceFromText(($<HTMLTextAreaElement>('evidenceNotes')).value.trim());if(required&&!payload)throw new Error('Add at least one current evidence source before approval.');return payload;}

function bindDetail(q:any,needsEvidence:boolean,anomaly:boolean){
 const decide=async(decision:'approve'|'needs_changes'|'reject')=>{const msg=$('decisionMsg');msg.textContent='Saving review decision…';try{const notes=($<HTMLTextAreaElement>('reviewNotes')).value.trim();const evidence=decision==='approve'?evidencePayload(needsEvidence):null;await reviewQuestion(q.id,decision,notes,evidence);msg.textContent='Review decision saved. Publishing remains a separate step.';await loadQueue();await openQuestion(q.id);}catch(e:any){msg.textContent=e.message||'Unable to save review.';}};
 const a=document.getElementById('approve');if(a)a.onclick=()=>decide('approve');$('changes').onclick=()=>decide('needs_changes');$('reject').onclick=()=>decide('reject');
 const p=document.getElementById('publish');if(p)p.onclick=async()=>{const msg=$('decisionMsg');if(!confirm('Publish this medically verified question to the public Verified QBank?'))return;msg.textContent='Publishing…';try{await publishQuestion(q.id,($<HTMLTextAreaElement>('reviewNotes')).value.trim());msg.textContent='Published to Verified QBank.';await loadQueue();await openQuestion(q.id);}catch(e:any){msg.textContent=e.message||'Unable to publish.';}};
 if(anomaly){const c=document.getElementById('saveCorrection');if(c)c.onclick=async()=>{const msg=$('correctionMsg');msg.textContent='Validating correction…';try{const evidence=evidenceFromText(($<HTMLTextAreaElement>('correctionEvidence')).value.trim());if(!evidence)throw new Error('Add at least one independent current evidence source.');const explanation=($<HTMLTextAreaElement>('correctedExplanation')).value.trim();const learning=($<HTMLTextAreaElement>('correctedLearning')).value.trim();const notes=($<HTMLTextAreaElement>('correctionNotes')).value.trim();const correctIndex=Number(($<HTMLSelectElement>('correctedIndex')).value);await correctQuarantinedQuestion(q.id,correctIndex,explanation,learning,notes,evidence);msg.textContent='Correction saved. The item is back in Evidence Review and still unpublished.';await loadQueue();await openQuestion(q.id);}catch(e:any){msg.textContent=e.message||'Unable to save correction.';}};}
 document.querySelectorAll<HTMLButtonElement>('[data-report]').forEach(b=>b.onclick=async()=>{const notes=prompt('Resolution / triage notes (optional):')||'';try{await resolveReport(b.dataset.report!,b.dataset.reportStatus as any,notes);await openQuestion(q.id);}catch(e:any){alert(e.message||'Unable to update report.');}});
}

async function loadTeam(){if(role!=='admin')return;const box=$('teamList');box.textContent='Loading reviewer team…';try{const team=await listReviewerTeam();renderTeam(team);}catch(e:any){box.textContent=e.message||'Unable to load reviewer team.';}}
function renderTeam(team:ReviewerTeamMember[]){const box=$('teamList');box.innerHTML=team.length?team.map(m=>`<div class="teamrow"><div><b>${esc(m.email||m.user_id)}</b><div class="muted">${esc(m.role)} · ${m.active?'active':'inactive'}</div></div><button data-team-email="${esc(m.email||'')}" data-team-role="${esc(m.role)}" data-team-active="${m.active?'0':'1'}">${m.active?'Deactivate':'Activate'}</button></div>`).join(''):'<div class="muted">No reviewer members yet.</div>';box.querySelectorAll<HTMLButtonElement>('[data-team-email]').forEach(b=>b.onclick=async()=>{const email=b.dataset.teamEmail!;if(!email)return;try{await setReviewerByEmail(email,b.dataset.teamRole as any,b.dataset.teamActive==='1');await loadTeam();}catch(e:any){$('teamMsg').textContent=e.message||'Unable to update reviewer.';}});}

$('addReviewer').onclick=async()=>{const email=($<HTMLInputElement>('reviewerEmail')).value.trim();const reviewerRole=($<HTMLSelectElement>('reviewerRole')).value as 'reviewer'|'lead_reviewer'|'admin';const msg=$('teamMsg');if(!email){msg.textContent='Enter the email of an existing SurgiQuiz account.';return;}msg.textContent='Adding reviewer…';try{await setReviewerByEmail(email,reviewerRole,true);msg.textContent='Reviewer access updated.';($<HTMLInputElement>('reviewerEmail')).value='';await loadTeam();}catch(e:any){msg.textContent=e.message||'Unable to add reviewer. The person must sign in to SurgiQuiz at least once first.';}};
$('createInvite').onclick=async()=>{const reviewerRole=($<HTMLSelectElement>('inviteRole')).value as 'reviewer'|'lead_reviewer'|'admin';const msg=$('inviteMsg');msg.textContent='Creating one-time invitation…';try{const inv=await createReviewerInvite(reviewerRole,7);($<HTMLInputElement>('generatedInvite')).value=inv.token;msg.textContent=`One-time ${inv.role.replaceAll('_',' ')} invitation created. Expires ${new Date(inv.expires_at).toLocaleString()}. Share the code privately; it is stored only as a hash in the database.`;}catch(e:any){msg.textContent=e.message||'Unable to create invitation.';}};

$('claimAdmin').onclick=async()=>{const msg=$('claimMsg');const token=($<HTMLInputElement>('claimToken')).value.trim();if(!token){msg.textContent='Enter the one-time claim code.';return;}msg.textContent='Claiming content administrator role…';try{await claimInitialContentAdmin(token);msg.textContent='Content administrator role activated.';($<HTMLInputElement>('claimToken')).value='';await init();}catch(e:any){msg.textContent=e.message||'Unable to claim administrator role.';}};
$('claimInvite').onclick=async()=>{const msg=$('reviewerInviteMsg');const token=($<HTMLInputElement>('reviewerInviteToken')).value.trim();if(!token){msg.textContent='Enter the reviewer invitation code.';return;}msg.textContent='Claiming reviewer invitation…';try{await claimReviewerInvite(token);msg.textContent='Reviewer access activated.';($<HTMLInputElement>('reviewerInviteToken')).value='';await init();}catch(e:any){msg.textContent=e.message||'Unable to claim reviewer invitation.';}};
$('reload').onclick=loadQueue;$('statusFilter').onchange=loadQueue;$('tierFilter').onchange=loadQueue;init();
