import { currentUser, getRevisionQueue, saveCloudProgress, type RevisionQuestion } from './student-cloud';
const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let completed=0,correct=0;
function updateSummary(){const summary=$('summary');summary.classList.toggle('hidden',completed===0);$('done').textContent=String(completed);$('right').textContent=String(correct);$('score').textContent=`${completed?Math.round(100*correct/completed):0}%`;}
async function answer(questionId:string,chosen:number,card:HTMLElement){const out=card.querySelector<HTMLElement>('.answer')!;card.querySelectorAll<HTMLButtonElement>('.opt').forEach(x=>x.disabled=true);try{const r=await fetch('/.netlify/functions/questions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'beta-answer',questionId})});if(!r.ok)throw new Error('answer');const d=await r.json();const a=d.answer;if(!a||a.answer_available===false||a.correct_index===null)throw new Error('unavailable');const isCorrect=chosen===Number(a.correct_index);completed++;if(isCorrect)correct++;await saveCloudProgress(questionId,chosen,isCorrect,null);out.classList.remove('hidden');out.innerHTML=`<strong>${isCorrect?'Correct':'Incorrect'}</strong><p>Correct option: ${String.fromCharCode(65+Number(a.correct_index))}</p>${a.en_explanation?`<p>${esc(a.en_explanation)}</p>`:''}`;updateSummary();}catch{out.classList.remove('hidden');out.textContent='Unable to load the answer right now.';card.querySelectorAll<HTMLButtonElement>('.opt').forEach(x=>x.disabled=false);}}
function reasonLabel(reason:string){if(reason==='incorrect')return 'Previous incorrect';if(reason==='bookmarked')return 'Bookmarked';if(reason==='weak-topic-unseen')return 'Weak domain · new item';return 'Revision priority';}
function render(qs:RevisionQuestion[]){const box=$('questions');box.innerHTML=qs.map((q,i)=>`<article class="card" data-id="${esc(q.id)}"><div><span class="badge">${i+1}/20</span><span class="badge">${esc(q.category)}</span><span class="badge">${esc(reasonLabel(q.reason))}</span></div><h3>${esc(q.en_stem)}</h3>${q.ar_stem?`<p dir="rtl">${esc(q.ar_stem)}</p>`:''}<div class="opts">${q.options.map(o=>`<button class="opt" data-choice="${o.index}">${String.fromCharCode(65+o.index)}. ${esc(o.en)}</button>`).join('')}</div><div class="answer hidden"></div></article>`).join('');document.querySelectorAll<HTMLButtonElement>('.opt').forEach(b=>b.onclick=()=>{const card=b.closest<HTMLElement>('[data-id]')!;answer(card.dataset.id!,Number(b.dataset.choice),card);});}
async function init(){const user=await currentUser();if(!user){$('status').innerHTML='Sign in first to build a personalized revision set. <a href="/student.html" style="color:white;font-weight:700">Open My Progress</a>';return;}try{const qs=await getRevisionQueue(20);if(!qs.length){$('status').textContent='Not enough performance data yet.';$('empty').classList.remove('hidden');return;}$('status').textContent=`${qs.length} questions selected from your current weak areas.`;render(qs);}catch(e:any){$('status').textContent=e?.message||'Unable to build the revision set right now.';}}
init();
