import { loadPublishedQuestions, type RemoteQuestion } from './question-api';
import { currentUser } from './student-cloud';
import { getPublishedLearning, getVerifiedStats, reportQuestion } from './trust';

const $=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const esc=(s:string)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let qs:RemoteQuestion[]=[];
let answered=new Set<string>();

async function loadStats(){try{const s=await getVerifiedStats();$('published').textContent=String(s.published||0);$('verified').textContent=String(s.verified||0);$('reviewed').textContent=String(s.medically_reviewed||0);$('total').textContent=String(s.total||0);}catch{/* stats are supplemental */}}

function render(){const box=$('qbox');if(!qs.length){box.className='card empty';box.innerHTML='<h2>No verified questions published yet.</h2><p class="muted">The transformed bank remains available in Full Book Beta while human medical review proceeds. Verified QBank will populate only after explicit reviewer approval and publication.</p>';return;}box.className='';box.innerHTML=qs.map(q=>`<article class="card question" data-q="${esc(q.id)}"><div class="top"><span class="badge">Verified · ${esc(q.category)}</span><span class="muted">${esc(q.topic)} · ${esc(q.difficulty)}</span></div><h3>${esc(q.en)}</h3>${q.ar&&q.ar!==q.en?`<p dir="rtl">${esc(q.ar)}</p>`:''}<div class="opts">${q.enOptions.map((o,i)=>`<button class="opt" data-i="${i}">${String.fromCharCode(65+i)}. ${esc(o)}</button>`).join('')}</div><div class="learning" hidden></div><div class="report"><details><summary>Report this question</summary><p class="muted">Reports are linked to the editorial workflow. Sign-in is required.</p><select class="reportType"><option value="medical_accuracy">Medical accuracy</option><option value="answer_issue">Answer issue</option><option value="outdated_evidence">Outdated evidence</option><option value="unclear_question">Unclear question</option><option value="translation">Translation</option><option value="reference">Reference</option><option value="technical">Technical</option><option value="other">Other</option></select><textarea class="reportNotes" placeholder="Describe the issue…"></textarea><button class="btn reportBtn">Submit report</button><span class="muted reportMsg"></span></details></div></article>`).join('');bind();}

function refText(r:any){if(typeof r==='string')return r;if(!r||typeof r!=='object')return String(r??'');const parts=[r.title,r.book,r.guideline,r.edition&&`Edition ${r.edition}`,r.chapter,r.year,r.pages,r.url].filter(Boolean);return parts.length?parts.join(' · '):JSON.stringify(r);}

function bind(){document.querySelectorAll<HTMLElement>('[data-q]').forEach(card=>{const id=card.dataset.q!;const q=qs.find(x=>x.id===id)!;card.querySelectorAll<HTMLButtonElement>('.opt').forEach(btn=>btn.onclick=async()=>{if(answered.has(id))return;const chosen=Number(btn.dataset.i);card.querySelectorAll<HTMLButtonElement>('.opt').forEach(x=>x.disabled=true);const out=card.querySelector<HTMLElement>('.learning')!;out.hidden=false;out.innerHTML='<p class="muted">Loading verified learning details…</p>';try{const l=await getPublishedLearning(id);if(!l||!l.trust?.published_verified)throw new Error('Verified learning details unavailable');answered.add(id);card.querySelectorAll<HTMLButtonElement>('.opt').forEach((x,i)=>{x.classList.toggle('correct',i===l.correct_index);x.classList.toggle('wrong',i===chosen&&i!==l.correct_index);});const rationale=new Map((l.options||[]).map(x=>[x.index,x]));out.innerHTML=`<div class="top"><div><b>${chosen===l.correct_index?'Correct':'Incorrect'}</b><div class="muted">Correct option ${String.fromCharCode(65+l.correct_index)}</div></div><span class="badge">Human medically reviewed</span></div>${l.en_explanation?`<h4>Explanation</h4><p>${esc(l.en_explanation)}</p>`:''}${l.en_learning_point?`<div class="lp"><b>Learning Point</b><p>${esc(l.en_learning_point)}</p></div>`:''}<h4>Why each option?</h4>${q.enOptions.map((o,i)=>`<div class="rationale"><b>${String.fromCharCode(65+i)}. ${esc(o)}</b><p>${esc(rationale.get(i)?.en_rationale||'Rationale not available.')}</p></div>`).join('')}<h4>References</h4><div class="refs">${(l.references||[]).map(r=>`<div class="ref">${esc(refText(r))}</div>`).join('')||'<div class="muted">No public reference metadata available.</div>'}</div><p class="muted">Content version ${l.content_version} · Medical review ${l.medical_reviewed_at?new Date(l.medical_reviewed_at).toLocaleDateString():'—'}${l.evidence_reviewed_at?` · Evidence review ${new Date(l.evidence_reviewed_at).toLocaleDateString()}`:''}</p>`;}catch(e:any){out.innerHTML=`<p class="muted">${esc(e.message||'Unable to load verified learning details.')}</p>`;card.querySelectorAll<HTMLButtonElement>('.opt').forEach(x=>x.disabled=false);}});const reportBtn=card.querySelector<HTMLButtonElement>('.reportBtn')!;reportBtn.onclick=async()=>{const msg=card.querySelector<HTMLElement>('.reportMsg')!;const type=(card.querySelector<HTMLSelectElement>('.reportType')!).value;const notes=(card.querySelector<HTMLTextAreaElement>('.reportNotes')!).value.trim();msg.textContent='Submitting…';try{if(!await currentUser())throw new Error('Sign in from My Progress before submitting a report.');await reportQuestion(id,type,notes);msg.textContent='Report submitted to the medical review workflow.';}catch(e:any){msg.textContent=e.message||'Unable to submit report.';}};});}

async function load(){const box=$('qbox');box.className='card empty';box.textContent='Loading Verified QBank…';try{qs=await loadPublishedQuestions(10);answered.clear();render();}catch{qs=[];box.innerHTML='<h2>Verified QBank is temporarily unavailable.</h2><p class="muted">Full Book Beta remains separate and accessible.</p>';}}

$('next').onclick=load;
await Promise.all([loadStats(),load()]);
